OEP: tenant impersonation
rancher/opni pull request #1013
Opened 2023-02-01 20:30 UTC by kralicky

2023-02-01 21:28 UTC, dbason requested changes

2023-02-01 21:28 UTC, dbason commented on enhancements/monitoring/20230131-tenant-impersonation.md
> +
Can we expand on this more, including diagrams of how you will envisage it working?

2023-02-01 22:45 UTC, dbason approved these changes

2023-02-06 19:24 UTC, sanjay920 submitted a review, later dismissed

2023-03-16 20:27 UTC, sanjay920 approved these changes

2023-03-16 20:27 UTC, merged