Add OEP draft: jwt auth provider
rancher/opni pull request #1027
Opened 2023-02-04 00:55 UTC by kralicky

2023-02-04 01:31 UTC, sanjay920 requested changes

2023-02-04 01:31 UTC, sanjay920 commented on enhancements/monitoring/20230203-jwt-auth-provider.md
> +Estimated time required: ~3 weeks
Can you break this down a little further?

2023-02-04 01:49 UTC, sanjay920 approved these changes

2023-11-21 22:37 UTC, kralicky commented
Closed as obsolete

2023-11-21 22:37 UTC, closed without merging