OEP: Cortex Config Options
rancher/opni pull request #1254
Opened 2023-03-28 21:33 UTC by kralicky

2023-03-29 16:13 UTC, sanjay920 requested changes
@kralicky @codyrancher can you add UI details to this OEP?

2023-03-29 19:15 UTC, dbason reviewed
As part of this did we want to move S3 configuration to a generic cluster wide setup?

2023-03-29 20:41 UTC, dbason approved these changes

2023-03-30 20:53 UTC, sanjay920 approved these changes

2023-03-30 20:53 UTC, merged