Onetime-token
rancher/opni pull request #1368
Opened 2023-05-01 01:59 UTC by dbason

Fixes #1366

2023-05-01 14:52 UTC, alexandreLamarre approved these changes

2023-05-01 15:59 UTC, kralicky requested changes

2023-05-01 15:59 UTC, kralicky commented on pkg/apis/core/v1/core.proto
> +  bool onetime = 7;
This should be implemented via a `maxUsages` field. Since usage counts are already tracked, that would integrate nicely with it.

2023-05-01 15:59 UTC, kralicky commented on pkg/bootstrap/server_v2.go
>  	}
This should not have to be changed, the storage backend should handle expiring the token when it has reached its usage count limit (see above comment)

2023-05-01 15:59 UTC, kralicky commented on pkg/storage/jetstream/token_store.go
> +		Onetime:      options.OneTime,
Need to implement this in all storage backends

2023-05-02 21:20 UTC, alexandreLamarre commented on pkg/opni/commands/tokens.go
> +	tokensCreateCmd.Flags().IntVar(&maxUsages, "max-usages", 0, "Maximum number of times this token can be used")
Since this is user facing, we should clarify here that 0 is unlimited

2023-05-02 22:05 UTC, kralicky approved these changes

2023-05-02 22:31 UTC, merged