Alertopsv2 API implementation
rancher/opni pull request #1394
Opened 2023-05-08 21:26 UTC by alexandreLamarre

2023-05-09 19:46 UTC, kralicky requested changes

2023-05-09 19:46 UTC, kralicky commented on pkg/util/errors.go
> +type IErrGroup struct {
Suggest renaming, this doesn't match go naming conventions.

2023-05-09 19:46 UTC, kralicky commented on pkg/util/init.go
> +type InitializerF interface {
This should probably stay within your plugin

2023-05-09 21:17 UTC, dbason approved these changes

2023-05-10 16:59 UTC, kralicky requested changes

2023-05-10 20:19 UTC, alexandreLamarre commented on plugins/alerting/pkg/alerting/alarms/v1/status.go
> +	}
rules take an evaluation period to run

2023-05-10 20:20 UTC, alexandreLamarre commented on pkg/util/errors.go
> +func (i *MultiErrGroup) Error() error {
I think `Combine` is better

2023-05-10 20:23 UTC, alexandreLamarre commented on plugins/alerting/pkg/alerting/alarms/v1/status.go
> +	eg, _ := errgroup.WithContext(ctxca)
no

2023-05-11 17:55 UTC, alexandreLamarre commented on plugins/alerting/pkg/alerting/alarms/v1/status.go
> +	}
it is technically configurable, but here its used as a heuristic

2023-05-11 18:03 UTC, alexandreLamarre commented on plugins/alerting/pkg/alerting/alarms/v1/status.go
> +	}
two things have to happen consecutively for the rule state to be accurate from cortex:

- a completed poll interval for persisted rule configs that checks if there are persisted configs that need to be loaded as prometheus rules. this is controlled via an independent poll config duration.
- a poll interval for loaded rules in memory that evaluates them w.r. to discovered metrics, one full evaluation is required to bring the rule from an unknown state to ok, firing, error, etc...

this is an opinionated heuristic where we omit handling a varierty of weird edge-case statuses in the setup phase, while also not passing on details of the setup implementation to the end user

2023-05-12 16:27 UTC, kralicky approved these changes

2023-05-12 19:34 UTC, merged