add http endpoints for UI
rancher/opni pull request #1516
Opened 2023-06-16 19:30 UTC by joshmeranda

2023-06-16 19:34 UTC, kralicky requested changes

2023-06-16 19:34 UTC, kralicky commented on plugins/metrics/pkg/apis/remoteread/remoteread.proto
> +      post: "/add"
Suggest renaming some of these to be more "RESTful", e.g. 
add: `POST /targets`
edit: `PUT /targets/{name}`
remove: `DELETE /targets/{name}`
list: `GET /targets`

2023-06-23 16:40 UTC, joshmeranda commented
@codyrancher 

waiting for https://github.com/rancher/opni/pull/1489 before merge

2023-06-23 16:42 UTC, kralicky submitted a review, later dismissed

2023-07-05 21:01 UTC, kralicky approved these changes

2023-07-06 16:26 UTC, merged