Topic/scaling Lock conformance & implementation changes
rancher/opni pull request #1797
Opened 2023-10-27 21:15 UTC by alexandreLamarre

2023-11-22 23:27 UTC, dbason approved these changes

2023-11-23 00:25 UTC, kralicky requested changes

2023-11-23 16:11 UTC, alexandreLamarre commented on pkg/test/testgrpc/lock.proto
> +  generate: true
yeah, its an internal test binary, which I use for testing the fault tolerance when the respective backends are unhealthy which is difficult to implement correctly in the storage test suite.

2023-11-24 15:21 UTC, alexandreLamarre commented
instance tracker code was saved in the branch `stash-instance-tracker`

2023-11-27 17:39 UTC, kralicky commented on pkg/storage/etcd/lock.go
> +var (
Are these still needed for etcd?

2023-11-28 16:57 UTC, kralicky approved these changes

2023-11-28 16:57 UTC, merged