Add opnictl tool
rancher/opni pull request #26
Opened 2021-04-29 22:30 UTC by galal-hussein

Add opnictl code to the opni repo

2021-05-03 23:23 UTC, tybalex approved these changes
I only reviewed the opnictl files, and they look good! I assume the go vendering files are fine.

one question I have is, will we have a file such as `values.yaml` basically contains any values of parameters used in other yaml files? For example, parameters such as `%ES_USER`, `%ES_PASSWORD`.
@galal-hussein

2021-05-03 23:28 UTC, galal-hussein commented
> I only reviewed the opnictl files, and they look good! I assume the go vendering files are fine.
> 
> one question I have is, will we have a file such as `values.yaml` basically contains any values of parameters used in other yaml files? For example, parameters such as `%ES_USER`, `%ES_PASSWORD`.
> @galal-hussein

no this is strictly is used within the opnictl tool, and will be utilized as flags that can be passed to the tool

2021-05-03 23:40 UTC, tybalex commented
> > I only reviewed the opnictl files, and they look good! I assume the go vendering files are fine.
> > one question I have is, will we have a file such as `values.yaml` basically contains any values of parameters used in other yaml files? For example, parameters such as `%ES_USER`, `%ES_PASSWORD`.
> > @galal-hussein
> 
> no this is strictly is used within the opnictl tool, and will be utilized as flags that can be passed to the tool

OK. I think in the future we should also make those hard-coded urls of nats and Elasticsearch (`NATS_URL` and `ES_ENDPOINT`) as variables, are you going to make these as flags with default values as well?

2021-05-04 00:05 UTC, AmartC requested changes
For Nats, please use nats-client.kube-system.svc. Currently,leading to errors.

2021-05-10 16:50 UTC, AmartC requested changes
Looks good for most part. However, please do update the documentation for what commands need to be run if using MacBook.

2021-05-11 22:37 UTC, tybalex commented on src/dashboard/Kibana/Dockerfile
> +FROM nikolaik/python-nodejs:python3.8-nodejs14-slim
not a must-do but it only needs python, so let's use `FROM python:3.8-slim`.

2021-05-12 00:33 UTC, merged