add aiops/apis
rancher/opni pull request #310
Opened 2022-06-28 23:14 UTC by kralicky

2022-07-05 21:05 UTC, dbason requested changes
Need to rebase from main to get dagger updates (or otherwise update the dagger version)

2022-07-12 19:41 UTC, tybalex approved these changes
the python part

2022-07-13 01:58 UTC, dbason submitted a review, later dismissed

2022-07-13 17:11 UTC, sanjay920 requested changes
@AmartC 
* squash commits that contain tiny changes to individual files, with better commit messages
* restore the bugfix in magefile.go that was made in [this commit](https://github.com/rancher/opni/pull/310/commits/72c7ca3a8a83fc220c9fce89e026c9c98cad5240)
* revert changes to cue.mod/pkg/universe.dagger.io/x/david@rawkode.dev/pulumi/up.sh 
  * this is a manual patch Joe had to make to this script

2022-07-14 18:03 UTC, sanjay920 approved these changes

2022-07-18 17:31 UTC, sanjay920 approved these changes

2022-07-18 23:31 UTC, sanjay920 approved these changes

2022-07-18 23:36 UTC, tybalex approved these changes

2022-07-18 23:51 UTC, merged