Cortex Service Discovery improvements & Disable SLO API
rancher/opni pull request #493
Opened 2022-08-11 19:49 UTC by alexandreLamarre

2022-08-11 21:31 UTC, dbason requested changes

2022-08-11 22:50 UTC, alexandreLamarre commented on pkg/metrics/unmarshal/unmarshal.go
> +func UnmarshallPrometheusWebResponse(resp *http.Response, lg *zap.SugaredLogger) (*response, error) {
done

2022-08-11 22:50 UTC, alexandreLamarre commented on plugins/cortex/pkg/cortex/prometheus_util.go
> +	val, err := unmarshal.UnmarshallPrometheusWebResponse(resp, lg)
done

2022-08-11 22:52 UTC, alexandreLamarre commented on plugins/slo/pkg/slo/simple.go
> +)
i think in the older implementation the sloth generator panicked on any`const` strings in its input, but yeah I've changed them to be `const` now

2022-08-12 01:09 UTC, dbason approved these changes

2022-08-12 01:22 UTC, merged