Alerting : Compute metrics
rancher/opni pull request #664
Opened 2022-10-14 17:22 UTC by alexandreLamarre

2022-11-11 20:21 UTC, kralicky requested changes

2022-11-14 15:39 UTC, alexandreLamarre commented on pkg/alerting/metrics/fs.go
> +	nodeFilters map[string]*alertingv1.FilesystemInfo,
Done

2022-11-14 15:40 UTC, alexandreLamarre commented on plugins/alerting/pkg/alerting/fetch_condition_info.go
> +					lock.Lock()
Reduced lock contention by using temp objects to aggregate over each individual cluster and locking once at the end of each spawned goroutine

2022-11-15 15:49 UTC, kralicky approved these changes

2022-11-15 16:19 UTC, merged