Create python base images
rancher/opni pull request #87
Opened 2021-08-10 23:48 UTC by dbason

2021-08-11 02:07 UTC, sanjay920 requested changes
minor changes requested

2021-08-11 02:07 UTC, sanjay920 commented on images/python/requirements.txt
> +schedule
can you set this version to `1.1.0`

2021-08-11 02:07 UTC, sanjay920 commented on images/python/requirements.txt
> +uvicorn==0.13.4
pls sort this file

2021-08-11 22:29 UTC, kralicky requested changes

2021-08-11 22:29 UTC, kralicky commented on images/python/Dockerfile
> +RUN cat /files-to-delete.txt | xargs rm -f
This might break on files containing spaces, suggest changing to 
`cat /files-to-delete.txt | xargs -d'\n' -- rm -f`

2021-08-11 23:16 UTC, kralicky approved these changes

2021-08-16 01:02 UTC, sanjay920 approved these changes

2021-08-16 01:30 UTC, merged